/* The following code was generated by JFlex 1.4.3 on 12/11/26 22:11 */

/*
 * CDDL HEADER START
 *
 * The contents of this file are subject to the terms of the
 * Common Development and Distribution License (the "License").  
 * You may not use this file except in compliance with the License.
 *
 * See LICENSE.txt included in this distribution for the specific
 * language governing permissions and limitations under the License.
 *
 * When distributing Covered Code, include this CDDL HEADER in each
 * file and include the License file at LICENSE.txt.
 * If applicable, add the following below this CDDL HEADER, with the
 * fields enclosed by brackets "[]" replaced with your own identifying
 * information: Portions Copyright [yyyy] [name of copyright owner]
 *
 * CDDL HEADER END
 */

/*
 * Copyright (c) 2009, 2010, Oracle and/or its affiliates. All rights reserved.
 */

/*
 * Cross reference a Fortran file
 */
package org.opensolaris.opengrok.analysis.fortran;
import org.opensolaris.opengrok.analysis.JFlexXref;
import java.io.IOException;
import java.io.Writer;
import java.io.Reader;
import org.opensolaris.opengrok.web.Util;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 12/11/26 22:11 from the specification file
 * <tt>/Users/takayuki/Workspace/SourceColon/src/main/java/org/opensolaris/opengrok/analysis/fortran/FortranXref.lex</tt>
 */
public class FortranXref extends JFlexXref {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 4;
  public static final int SCOMMENT = 6;
  public static final int LCOMMENT = 10;
  public static final int QSTRING = 8;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6, 6
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\1\1\3\1\0\1\1\1\2\22\0\1\1\1\27\1\25"+
    "\1\33\2\6\1\32\1\26\2\33\1\31\2\6\1\10\1\11\1\15"+
    "\1\16\11\5\1\41\1\6\1\23\1\6\1\24\1\6\1\42\2\20"+
    "\1\14\2\20\1\40\1\4\1\34\1\12\4\4\1\13\1\4\1\36"+
    "\2\4\1\37\1\35\3\4\1\17\2\4\1\33\1\30\2\33\1\7"+
    "\1\33\2\20\1\14\1\22\1\20\1\40\1\4\1\34\1\12\2\4"+
    "\1\21\1\4\1\13\1\4\1\36\2\4\1\37\1\35\1\21\2\4"+
    "\1\17\2\4\3\33\1\6\uff81\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\7\0\1\1\1\2\2\3\1\4\1\5\1\4\1\5"+
    "\1\6\1\7\1\10\1\11\1\12\1\13\1\14\1\5"+
    "\3\4\1\6\1\15\4\4\1\2\2\16\1\17\1\4"+
    "\1\20\1\21\1\0\1\5\12\0\1\22\1\23\2\0"+
    "\1\24\1\0\1\25\2\5\6\0\1\2\5\0\1\26"+
    "\5\0\1\27\1\30\2\0\1\31\2\0\1\32";

  private static int [] zzUnpackAction() {
    int [] result = new int[86];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\43\0\106\0\151\0\214\0\257\0\322\0\365"+
    "\0\u0118\0\u013b\0\365\0\u015e\0\u0181\0\365\0\u01a4\0\u01c7"+
    "\0\365\0\365\0\365\0\365\0\365\0\u01ea\0\u020d\0\u0230"+
    "\0\u0253\0\u0276\0\365\0\u0299\0\u02bc\0\u02df\0\u0302\0\u0325"+
    "\0\u0348\0\u036b\0\365\0\u038e\0\u03b1\0\365\0\u015e\0\u03d4"+
    "\0\u03f7\0\u041a\0\u043d\0\u0460\0\u0230\0\u0483\0\u04a6\0\u04c9"+
    "\0\u0253\0\u04ec\0\u050f\0\365\0\365\0\u0532\0\u0555\0\365"+
    "\0\u0578\0\365\0\u059b\0\u05be\0\u05e1\0\u0604\0\u0627\0\u064a"+
    "\0\u066d\0\u0690\0\365\0\u06b3\0\u06d6\0\u06f9\0\u071c\0\u073f"+
    "\0\u0762\0\u0785\0\u07a8\0\u07cb\0\u07ee\0\u0811\0\u0230\0\u0785"+
    "\0\u0834\0\u0857\0\365\0\u087a\0\u089d\0\u089d";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[86];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\14"+
    "\2\16\3\14\1\16\1\17\4\14\1\20\1\21\1\22"+
    "\1\23\1\24\2\16\1\25\1\16\5\14\2\16\1\26"+
    "\1\11\1\12\1\13\1\26\1\27\10\26\1\27\24\26"+
    "\1\10\1\11\1\12\1\13\1\30\1\31\1\16\3\31"+
    "\3\30\1\32\1\31\4\30\1\33\1\21\1\34\2\16"+
    "\1\35\1\16\1\25\1\16\1\36\3\30\1\37\2\16"+
    "\1\10\1\11\1\12\1\13\1\30\1\31\1\16\3\31"+
    "\3\30\1\32\1\31\4\30\1\33\1\21\4\16\1\40"+
    "\1\25\1\16\1\36\3\30\1\37\2\16\1\10\1\41"+
    "\1\42\1\43\1\30\1\31\1\16\3\31\3\30\1\32"+
    "\1\31\4\30\1\33\1\21\5\16\1\25\1\16\1\36"+
    "\3\30\1\37\2\16\1\10\1\11\1\12\1\13\1\30"+
    "\1\31\1\16\3\31\3\30\1\32\1\31\4\30\1\33"+
    "\1\21\1\16\1\44\1\16\1\45\1\16\1\25\1\16"+
    "\1\36\3\30\1\37\2\16\1\46\1\41\1\42\1\43"+
    "\17\16\1\33\1\21\5\16\1\25\10\16\44\0\1\11"+
    "\1\12\1\13\42\0\1\13\43\0\2\47\1\0\1\47"+
    "\2\0\3\47\1\0\5\47\11\0\5\47\7\0\1\15"+
    "\3\0\1\50\4\0\1\15\2\0\2\51\25\0\1\15"+
    "\3\0\1\50\4\0\1\15\1\52\1\0\2\51\24\0"+
    "\1\53\5\0\3\53\1\54\1\0\4\53\11\0\5\53"+
    "\2\0\1\26\3\0\40\26\3\0\1\26\1\27\10\26"+
    "\1\27\24\26\4\0\2\55\1\0\2\55\1\56\3\55"+
    "\1\57\5\55\11\0\5\55\1\0\1\60\4\0\2\61"+
    "\1\0\6\61\1\0\5\61\11\0\5\61\1\0\1\60"+
    "\4\0\1\62\5\0\3\62\2\0\4\62\11\0\5\62"+
    "\3\0\1\63\66\0\1\64\2\0\1\65\16\0\2\55"+
    "\1\0\2\55\1\56\3\55\1\57\5\55\11\0\1\55"+
    "\1\66\3\55\1\0\1\60\4\0\2\55\1\0\2\55"+
    "\1\56\3\55\1\57\5\55\11\0\1\55\1\67\3\55"+
    "\1\0\1\60\15\0\1\70\26\0\1\41\1\42\1\43"+
    "\42\0\1\43\40\0\1\71\67\0\1\72\1\0\1\65"+
    "\17\0\1\73\10\0\1\73\45\0\2\51\25\0\1\74"+
    "\6\0\1\74\1\0\1\74\1\0\1\74\1\0\1\74"+
    "\15\0\1\74\6\0\2\53\1\0\2\53\1\75\3\53"+
    "\1\76\5\53\11\0\5\53\6\0\1\77\5\0\3\77"+
    "\2\0\4\77\11\0\5\77\6\0\2\55\1\0\2\55"+
    "\1\56\1\100\2\55\1\57\5\55\11\0\5\55\1\0"+
    "\1\60\4\0\1\101\5\0\3\101\2\0\4\101\11\0"+
    "\5\101\6\0\2\102\1\0\6\102\1\0\5\102\11\0"+
    "\5\102\6\0\2\62\1\0\6\62\1\57\5\62\11\0"+
    "\5\62\3\0\1\63\23\0\1\103\21\0\2\55\1\0"+
    "\2\55\1\56\3\55\1\57\5\55\11\0\1\55\1\104"+
    "\3\55\1\0\1\60\4\0\2\55\1\0\2\55\1\56"+
    "\3\55\1\57\5\55\11\0\2\55\1\105\2\55\1\0"+
    "\1\60\1\0\1\71\24\0\1\103\21\0\1\73\10\0"+
    "\1\73\2\0\2\51\25\0\1\74\6\0\1\74\1\0"+
    "\1\74\1\0\1\74\1\51\1\74\15\0\1\74\6\0"+
    "\2\53\1\0\2\53\1\75\1\106\2\53\1\76\5\53"+
    "\11\0\5\53\6\0\1\107\5\0\3\107\2\0\4\107"+
    "\11\0\5\107\6\0\2\77\1\0\6\77\1\76\5\77"+
    "\11\0\5\77\6\0\2\55\1\0\2\55\1\56\1\55"+
    "\1\110\1\55\1\57\5\55\11\0\5\55\1\0\1\60"+
    "\4\0\2\111\1\0\3\101\3\111\1\0\5\111\11\0"+
    "\5\111\6\0\2\102\1\0\2\102\1\112\3\102\1\0"+
    "\5\102\11\0\5\102\6\0\2\55\1\0\2\55\1\56"+
    "\3\55\1\57\5\55\11\0\2\55\1\113\2\55\1\0"+
    "\1\60\4\0\2\55\1\0\2\55\1\56\3\55\1\57"+
    "\5\55\11\0\5\55\1\114\1\60\4\0\2\53\1\0"+
    "\2\53\1\75\1\53\1\115\1\53\1\76\5\53\11\0"+
    "\5\53\6\0\2\116\1\0\3\107\3\116\1\0\5\116"+
    "\11\0\5\116\6\0\2\55\1\0\2\55\1\56\2\55"+
    "\1\117\1\57\5\55\11\0\5\55\1\0\1\60\4\0"+
    "\2\111\1\0\3\101\3\111\1\57\5\111\11\0\5\111"+
    "\6\0\2\120\1\0\6\120\1\0\5\120\11\0\5\120"+
    "\6\0\2\55\1\0\2\55\1\56\3\55\1\57\5\55"+
    "\11\0\3\55\1\105\1\55\1\114\1\60\15\0\1\121"+
    "\31\0\2\53\1\0\2\53\1\75\2\53\1\122\1\76"+
    "\5\53\11\0\5\53\6\0\2\116\1\0\3\107\3\116"+
    "\1\76\5\116\1\0\1\123\7\0\5\116\17\0\1\124"+
    "\31\0\2\53\1\0\2\53\1\75\3\53\1\76\5\53"+
    "\1\0\1\123\7\0\5\53\6\0\17\125\4\0\4\125"+
    "\1\0\7\125\4\0\2\126\4\125\11\126\4\0\4\125"+
    "\1\0\5\126\2\125";

  private static int [] zzUnpackTrans() {
    int [] result = new int[2240];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\7\0\1\11\2\1\1\11\2\1\1\11\2\1\5\11"+
    "\5\1\1\11\7\1\1\11\2\1\1\11\1\1\1\0"+
    "\1\1\12\0\2\11\2\0\1\11\1\0\1\11\2\1"+
    "\6\0\1\11\5\0\1\1\5\0\2\1\2\0\1\11"+
    "\2\0\1\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[86];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  // TODO move this into an include file when bug #16053 is fixed
  @Override
  protected int getLineNumber() { return yyline; }
  @Override
  protected void setLineNumber(int x) { yyline = x; }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public FortranXref(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public FortranXref(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 150) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      if (zzMarkedPosL > zzStartRead) {
        switch (zzBufferL[zzMarkedPosL-1]) {
        case '\n':
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          zzAtBOL = true;
          break;
        case '\r': 
          if (zzMarkedPosL < zzEndReadL)
            zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          else if (zzAtEOF)
            zzAtBOL = false;
          else {
            boolean eof = zzRefill();
            zzMarkedPosL = zzMarkedPos;
            zzEndReadL = zzEndRead;
            zzBufferL = zzBuffer;
            if (eof) 
              zzAtBOL = false;
            else 
              zzAtBOL = zzBufferL[zzMarkedPosL] != '\n';
          }
          break;
        default:
          zzAtBOL = false;
        }
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      if (zzAtBOL)
        zzState = ZZ_LEXSTATE[zzLexicalState+1];
      else
        zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 5: 
          { out.write("<span class=\"n\">"); out.write(yytext()); out.write("</span>");
          }
        case 27: break;
        case 4: 
          { out.write(yycharat(0));
          }
        case 28: break;
        case 9: 
          { yybegin(QSTRING);out.write("<span class=\"s\">\'");
          }
        case 29: break;
        case 19: 
          { out.write("\\\\");
          }
        case 30: break;
        case 8: 
          { yybegin(STRING);out.write("<span class=\"s\">\"");
          }
        case 31: break;
        case 14: 
          { yybegin(YYINITIAL); out.write("</span>");
                  startNewLine();
          }
        case 32: break;
        case 13: 
          { yybegin(YYINITIAL); out.write("\"</span>");
          }
        case 33: break;
        case 21: 
          { out.write("\\\'");
          }
        case 34: break;
        case 12: 
          { String commentStr = yytext(); yybegin(LCOMMENT);out.write("<span class=\"c\">"+commentStr);
          }
        case 35: break;
        case 16: 
          { writeUnicodeChar(yycharat(0));
          }
        case 36: break;
        case 11: 
          { out.write( "&amp;");
          }
        case 37: break;
        case 15: 
          { yybegin(YYINITIAL); out.write("'</span>");
          }
        case 38: break;
        case 6: 
          { out.write( "&lt;");
          }
        case 39: break;
        case 24: 
          { writeEMailAddress(yytext());
          }
        case 40: break;
        case 3: 
          { startNewLine();
          }
        case 41: break;
        case 26: 
          { String url = yytext();
         out.write("<a href=\"");
         out.write(url);out.write("\">");
         out.write(url);out.write("</a>");
          }
        case 42: break;
        case 18: 
          { out.write("\\\"");
          }
        case 43: break;
        case 23: 
          { String path = yytext();
        out.write("<a href=\""+urlPrefix+"path=");
        out.write(path);out.write("\">");
        out.write(path);out.write("</a>");
          }
        case 44: break;
        case 2: 
          { out.write(yytext());
          }
        case 45: break;
        case 20: 
          { yybegin(YYINITIAL); out.write("*/</span>");
          }
        case 46: break;
        case 7: 
          { out.write( "&gt;");
          }
        case 47: break;
        case 17: 
          { String id = yytext();
    writeSymbol(id, Consts.kwd, yyline);
          }
        case 48: break;
        case 22: 
          { out.write(Util.breadcrumbPath(urlPrefix+"path=",yytext(),'/'));
          }
        case 49: break;
        case 10: 
          { yybegin(SCOMMENT);out.write("<span class=\"c\">!");
          }
        case 50: break;
        case 25: 
          { out.write("&lt;");
    String file = yytext();
    file = file.substring(1, file.length() - 1);
    out.write("<a href=\""+urlPrefix+"path=");
    out.write(file);out.write("\">");
    out.write(file);out.write("</a>");
    out.write("&gt;");
          }
        case 51: break;
        case 1: 
          { 
          }
        case 52: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return YYEOF;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
